### ISSUE TITLE
Up button visibility & text

### ISSUE THREAD

**Issue by Tweekism** [jannis-baum/Vivify#81]
Hi Team,

I was going to suggest a back button for navigation up the directory structure until I discovered you already have one. However by default it is invisible until it is hovered over, not sure if that was the intention?

![viv_parent_link](https://github.com/user-attachments/assets/ff108180-abc4-443e-a659-1ed3186c0906)

```css
a#parent-dir {
    position: fixed;
    height: 3rem; width: 3rem;
    line-height: 3rem; text-align: center;
    background-color: #333;
    border-radius: 9999px;
    left: 2rem; top: 2rem;
    opacity: 0;
}
a#parent-dir:hover { opacity: 1; }
```
